<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-3V017FK" failures="1" tests="4" name="listener.SampleTest2" time="0.018" errors="0" timestamp="2023-06-29T17:11:35 IST" skipped="1">
  <testcase classname="listener.SampleTest2" name="tc8" time="0.000">
    <system-out>
      <![CDATA[test tc8execution start
tc8 is running
thistc8 method is compleated successfully]]>
    </system-out>
  </testcase> <!-- tc8 -->
  <testcase classname="listener.SampleTest2" name="tc7" time="0.000">
    <skipped/>
    <system-out>
      <![CDATA[thistc7 Tc is skipped.. please check dependent method ]]>
    </system-out>
  </testcase> <!-- tc7 -->
  <testcase classname="listener.SampleTest2" name="tc5" time="0.004">
    <system-out>
      <![CDATA[test tc5execution start
tc5 is running
thistc5 method is compleated successfully]]>
    </system-out>
  </testcase> <!-- tc5 -->
  <testcase classname="listener.SampleTest2" name="tc6" time="0.014">
    <failure message="null" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: null
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.fail(Assert.java:116)
at listener.SampleTest2.tc6(SampleTest2.java:19)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:577)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:227)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:957)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:200)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:848)
at org.testng.TestRunner.run(TestRunner.java:621)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1280)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1200)
at org.testng.TestNG.runSuites(TestNG.java:1114)
at org.testng.TestNG.run(TestNG.java:1082)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
    <system-out>
      <![CDATA[test tc6execution start
thistc6 method is failed please try again]]>
    </system-out>
  </testcase> <!-- tc6 -->
  <system-out>
    <![CDATA[test tc6execution start
thistc6 method is failed please try again
test tc5execution start
tc5 is running
thistc5 method is compleated successfully
test tc8execution start
tc8 is running
thistc8 method is compleated successfully
test tc7execution start
thistc7 Tc is skipped.. please check dependent method 
test TC1execution start
TC1 is Rinning
thisTC1 method is compleated successfully
test TC2execution start
thisTC2 method is failed please try again
test TC4execution start
TC4 is Rinning
thisTC4 method is compleated successfully
test TC3execution start
thisTC3 Tc is skipped.. please check dependent method ]]>
  </system-out>
</testsuite> <!-- listener.SampleTest2 -->
